package org.example.languageDetectionAndCrackingCaesar;

import org.example.caesarCipher.CaesarCipherBruteForce;

public class LanguageDetectionAndCrackingCaesarApp {

    public static void main(String[] args){
        CaesarCipherBruteForce cracker = new CaesarCipherBruteForce();
        cracker.crack("FRPSLOLQJ!D!MDYD!SURJUDP%!D!FRPSLOHU!LV!DQ!DSSOLFDWLRQ!WKDW!WUDQVODWHV!SURJUDPV!IURP!WKH!MDYD!ODQJXDJH!WR!D!ODQJXDJH!PRUH!VXLWDEOH!IRU!H HFXWLQJ!RQ!WKH!FRPSXWHU%!LW!WDNHV!D!WH W!ILOH!ZLWK!WKH!%MDYD!H WHQVLRQ!DV!LQSXW!A.RXU!SURJUDPB!DQG!SURGXFHV!D!ILOH!ZLWK!D!%FODVV!H WHQVLRQ!AWKH!FRPSXWHUCODQJXDJH!YHUVLRQB%!WR!FRPSLOH!KHOORZRUOG%MDYD!W.SH!WKH!EROGIDFHG!WH W!EHORZ!DW!WKH!WHUPLQDO%!AZH!XVH!WKH!-!V.PERO!WR!GHQRWH!WKH!FRPPDQG!SURPSW(!EXW!LW!PD.!DSSHDU!GLIIHUHQW!GHSHQGLQJ!RQ!.RXU!V.VWHP%B");
    }
}
